// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToursWebAppEXAMProject.DBContext;

#nullable disable

namespace ToursWebAppEXAMProject.Migrations
{
    [DbContext(typeof(TourFirmaDBContext))]
    [Migration("20260610124622__AddedPublicIdForImages")]
    partial class _AddedPublicIdForImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.AboutPageVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutFullDescription")
                        .HasColumnType("text");

                    b.Property<string>("AboutImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AboutImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AboutShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AboutTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsFullDescription")
                        .HasColumnType("text");

                    b.Property<string>("DetailsImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DetailsImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailsShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DetailsTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FeedbackFullDescription")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FeedbackImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedbackShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FeedbackTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActual")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MainFullDescription")
                        .HasColumnType("text");

                    b.Property<string>("MainImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MainImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MainShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MainTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperationModeFullDescription")
                        .HasColumnType("text");

                    b.Property<string>("OperationModeImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OperationModeImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperationModeShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperationModeTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhotoGalleryFullDescription")
                        .HasColumnType("text");

                    b.Property<string>("PhotoGalleryImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoGalleryImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoGalleryShortDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhotoGalleryTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AboutPageVersions");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Asker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Askers");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("('Полное описание темы блога')");

                    b.Property<string>("FullMessageLine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("('Вся строка сообщений')");

                    b.Property<string>("ImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasDefaultValue("('Сообщение')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("('Заголовок блога')");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("('Краткое описание темы блога')");

                    b.Property<string>("TitleImagePath")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("('Нет титульной картинки')");

                    b.HasKey("Id");

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("('Полное описание города')");

                    b.Property<string>("ImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalDescription")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("('Название города')");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasDefaultValue("('Краткое описание города')");

                    b.Property<string>("TitleImagePath")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("('Нет титульной картинки города')");

                    b.Property<bool>("isCapital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Correspondence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("AnswerDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AskerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("QuestionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AskerId");

                    b.ToTable("Correspondences");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("('Столица страны')");

                    b.Property<string>("CountryMapPath")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("('Нет ссылки на карту страны в GoogleMaps')");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("('Полное описание страны')");

                    b.Property<string>("ImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("('Название страны')");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasDefaultValue("('Краткое описание страны')");

                    b.Property<string>("TitleImagePath")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("('Нет титульной картинки страны')");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.DateTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfNights")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DateTour", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ModeOfEating")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Food", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("LevelHotel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotel", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.New", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("('Полное описание новости')");

                    b.Property<string>("ImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("('Заголовок новости')");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasDefaultValue("('Краткое описание новости')");

                    b.Property<string>("TitleImagePath")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("('Нет титульной картинки')");

                    b.HasKey("Id");

                    b.ToTable("New", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("SallerId")
                        .HasColumnType("integer");

                    b.Property<int>("TourId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SallerId");

                    b.HasIndex("TourId");

                    b.ToTable("Offer", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.PhotoGalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AboutPageVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AboutPageVersionId");

                    b.ToTable("PhotoGalleryImages");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("('Полное описание туристического продукта')");

                    b.Property<string>("ImagePublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("('Название туристического продукта')");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasDefaultValue("('Краткое описание туристического продукта')");

                    b.Property<string>("TitleImagePath")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("('Нет титульной картинки')");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Saller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("('сотрудник')");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Saller", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.TechTaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TechTaskPageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("TechTaskPageId");

                    b.ToTable("TechTaskItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Данная страница д.содержать:\r\n			<br /><strong>блок навигационных кнопок:</strong>\r\n			\"Новости со всего мира\", \"Блоги о туризме\", \"ТЗ для Home\"\r\n			<br /><strong>большую пейзажную фоновую картинку</strong>\r\n			(м.б. море, тропический остров с пальмами)\r\n			<br /><strong>списки новостей и блогов о туризме с вертикальными скроллами</strong>,\r\n			которые загружаются при открытии страницы вертикальными полосами слева и справа;",
                            IsCompleted = false,
                            OrderNumber = 1,
                            TechTaskPageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Д.б. создана <strong>страница со списком новостей</strong>,\r\n			которая открывается по нажатию на кнопку\r\n			<strong>\"Новости со всего мира\"</strong>.\r\n			<br />В списке новостей <strong>для каждой новости</strong>\r\n			указываются:\r\n			титульная картинка,\r\n			название новости,\r\n			краткое описание,\r\n			полное описание,\r\n			ссылка на полное описание.\r\n			<br />При нажатии на ссылку\r\n			<strong>\"Подробнее\"</strong>\r\n			открывается новость с:\r\n			титульной картинкой,\r\n			названием,\r\n			полным описанием,\r\n			id новости и датой сохранения.",
                            IsCompleted = false,
                            OrderNumber = 2,
                            TechTaskPageId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Д.б. создана <strong>страница со списком блогов</strong>,\r\n			которая открывается по нажатию на кнопку\r\n			<strong>\"Блоги о туризме\"</strong>.\r\n			<br />В списке блогов <strong>для каждого блога</strong>\r\n			указываются:\r\n			титульная картинка,\r\n			название блога,\r\n			краткое описание,\r\n			ссылка на полное описание.\r\n			<br />При нажатии на ссылку\r\n			<strong>\"Подробнее\"</strong>\r\n			открывается блог с:\r\n			титульной картинкой,\r\n			названием,\r\n			полным описанием,\r\n			сообщениями блоггеров,\r\n			id блога и датой сохранения.",
                            IsCompleted = false,
                            OrderNumber = 3,
                            TechTaskPageId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Д.б. реализована\r\n			<strong>возможность создания текстовых сообщений блоггеров,\r\n			редактирования и удаления со стороны редактора сайта</strong>.\r\n			<br />Д.б. реализован\r\n			<strong>механизм получения, пересылки и сохранения текстовых сообщений блоггеров</strong>.",
                            IsCompleted = false,
                            OrderNumber = 4,
                            TechTaskPageId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Д.б. реализована\r\n			<strong>функциональность оценивания прогресса выполнения технических задач\r\n			для каждой страницы</strong>.\r\n			<br />По нажатию на кнопки:\r\n			<strong>\"ТЗ для Home\"</strong>,\r\n			<strong>\"ТЗ для Search\"</strong>,\r\n			<strong>\"ТЗ для Admin\"</strong>,\r\n			<strong>\"ТЗ для Support\"</strong>,\r\n			<strong>\"ТЗ для About\"</strong>\r\n			открываются соответствующие страницы\r\n			со шкалой прогресса\r\n			и возможностью редактирования и сохранения выполненных ТЗ.",
                            IsCompleted = false,
                            OrderNumber = 5,
                            TechTaskPageId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Дополнительно:\r\n			<br />М.б. создан\r\n			<strong>дополнительный функционал:</strong>\r\n			<strong>\"последние прочитанные новости/блоги\"</strong>,\r\n			<strong>\"статистика прочтения новостей/\r\n			написания сообщений в блогах\"</strong>,\r\n			<strong>\"чаще всего читают новости/блоги\"</strong>\r\n			и т.д.",
                            IsCompleted = false,
                            OrderNumber = 6,
                            TechTaskPageId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Данная страница д.содержать:\r\n							<br /><strong>блок навигационных кнопок: </strong> \"Поиск туров\", \"Все турпродуктв\", \"Все страны\", \"Все города\", \"ТЗ для Search\"\r\n							< br />< strong > меню поиска:</ strong > страны,\r\n					города,\r\n					дат тура,\r\n					количества туристов и кнопка \"Найти тур\"\r\n							< br />< strong > информативное меню:</ strong > карта местности и описания страны,\r\n					города,\r\n					достопримечательностей\r\n							< br />< strong > галерея с фото:</ strong > фотографии страны,\r\n					городов,\r\n					достопримечательностей\r\n\r\n							< br /> По нажатию на кнопку < strong > \"Поиск туров\" или \"Найти тур\" </ strong > осуществляется < strong > функционал поиска турпродукта по заданным параметрам поиска </ strong > и выводится < strong > список всех найденных туристических продуктов </ strong > с вертикальным скроллом",
                            IsCompleted = false,
                            OrderNumber = 1,
                            TechTaskPageId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "<strong>Меню поиска</strong> д.содержать: \r\n							<br/><strong>выпадающий список стран</strong> (элемент radiobutton - выбор только 1 страны);\r\n							<br/><strong>выпадающие календари</strong> с <strong>датами начала и окончания тура</strong>);\r\n							<br/><strong>выпадающий список - количество дней/ночей</strong> (элемент select - выбор 1 или больше вариантов);\r\n							<br/><strong>выпадающий список людей</strong> (взрослых) + возможность добавить детей (количество и возраст детей) (по умолчанию - 2 взрослых, без детей)\r\n							<br/><strong>кнопка \"Найти тур\"</strong>;\r\n							< br /> Д.б.организован < strong > поиск туристических продуктов по заданным параметрам </ strong > ",
                            IsCompleted = false,
                            OrderNumber = 2,
                            TechTaskPageId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "<strong>Информативное меню</strong> под меню поиска, д. содержать:\r\n							<br/><strong>раскрытый список городов</strong> данной страны;\r\n							<br />(элемент select - выбор 1 или больше городов) (расположено - под страной) (при выборе страны - появляются города этой страны);\r\n							<br/><strong>д.б. карта местности</strong> (рядом с городами):\r\n							<br/><strong>описание:</strong>\r\n							<br />при выборе страны - в верхней трети - появляется <strong>описание о стране</strong>\r\n							<br />при выборе города - в средней трети - появляется <strong>описание о городе</strong>\r\n							<br />а в нижней трети - появляется <strong>описание о достопримечательности</strong>",
                            IsCompleted = false,
                            OrderNumber = 3,
                            TechTaskPageId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Д.б. реализована <strong>возможность просматривать карту страны</strong>, с нанесенными на нее городами и турпродуктами\r\n							",
                            IsCompleted = false,
                            OrderNumber = 4,
                            TechTaskPageId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Д.б. реализована <strong>галерея с фото страны, городов и достопримечательностей</strong>\r\n							<br />выводятся все фото, кот. есть в базе; если их много и они не помещаются, то появляется горизонт. скроллинг<br/>",
                            IsCompleted = false,
                            OrderNumber = 5,
                            TechTaskPageId = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Дополнительно:\r\n							<br />м.б. реализована <strong>галерея с фото из гостинниц, кафе, других мест</strong>",
                            IsCompleted = false,
                            OrderNumber = 6,
                            TechTaskPageId = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Данная страница д. содержать:\r\n							<br/><strong>блок навигационных кнопок: </strong> \"Редактировать новости\", \"Редактировать блоги\", \"Редактировать турпродукты\", \"ТЗ для Edit\";\r\n							< br />< strong > общее меню поиска сущностей(новостей / блогов / турпродуктов) по их полному названию / или по ключевому слову </ strong > из названия сущности для выборки из БД;\r\n							< br />< strong > страницу со списком выбранных сущностей </ strong >,\r\n					отвечающих критериям поиска.",
                            IsCompleted = false,
                            OrderNumber = 1,
                            TechTaskPageId = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "Д.б. создана <strong>страница создания, редактирования и удаления новости</strong>, ее названия, краткого и полного описания, пути к титульной картинке",
                            IsCompleted = false,
                            OrderNumber = 2,
                            TechTaskPageId = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Д.б. создана <strong>страница создания, редактирования и удаления блога</strong>, его названия, краткого и полного описания, пути к титульной картинке",
                            IsCompleted = false,
                            OrderNumber = 3,
                            TechTaskPageId = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Д.б. создана <strong>страница создания, редактирования и удаления туристического продукта</strong>, его названия, краткого и полного описания, пути к титульной картинке",
                            IsCompleted = false,
                            OrderNumber = 4,
                            TechTaskPageId = 3
                        },
                        new
                        {
                            Id = 17,
                            Description = "Д.б. организован <strong>доступ для входа на страницу - для редактирования данных БД</strong> - только для сотрудников турфирмы, у кот. <strong> роль \"superadmin\" илм \"editor\"</strong>",
                            IsCompleted = false,
                            OrderNumber = 5,
                            TechTaskPageId = 3
                        },
                        new
                        {
                            Id = 18,
                            Description = "Дополнительно:\r\n							<br />М.б. созданы <strong>3 роли с разным доступом: </strong>\r\n							<br />М.б. создана <strong>страница создания, редактирования и удаления страны</strong>, ее названия, краткого и полного описания, пути к титульной картинке\r\n							<br />М.б. создана <strong>страница создания, редактирования и удаления города</strong>, его названия, краткого и полного описания, пути к титульной картинке",
                            IsCompleted = false,
                            OrderNumber = 6,
                            TechTaskPageId = 3
                        },
                        new
                        {
                            Id = 19,
                            Description = "Данная страница д. содержать:\r\n							<br /><strong>блок навигационных кнопок:</strong> \"Перевод текста\", \"Карта\" или \"Прогноз погоды\", \"ТЗ для Support\";\r\n							< br /> по нажатию на кнопку < strong > \"Перевод текста\" </ strong > -раскрывается область,\r\n					в кот.слева - текст,\r\n					кот.\r\n							н.перевести,\r\n					а справа - перевод на иностр.язык\r\n							< br /> по нажатию на кнопку < strong > \"Карта\" </ strong > -раскрывается область,\r\n					в кот.появляется карта данной местности\r\n							< br /> по нажатию на кнопку < strong > \"Прогноз погоды\" </ strong > -раскрывается область,\r\n					в кот.появляется прогноз погоды для данной местности",
                            IsCompleted = false,
                            OrderNumber = 1,
                            TechTaskPageId = 4
                        },
                        new
                        {
                            Id = 20,
                            Description = "Д.б. создана <strong>страница с возможностью перевода текстов на иностранный язык</strong> с использованием <strong>Google Translate API</strong>",
                            IsCompleted = false,
                            OrderNumber = 2,
                            TechTaskPageId = 4
                        },
                        new
                        {
                            Id = 21,
                            Description = "Д.б. создана <strong>страница с выводимой картой местности</strong>, с использованием <strong>Google Map API</strong>",
                            IsCompleted = false,
                            OrderNumber = 3,
                            TechTaskPageId = 4
                        },
                        new
                        {
                            Id = 22,
                            Description = "М.б. создана <strong>страница с прогнозом погоды для данной местности</strong>, с использованием <strong>Open Weather API</strong>",
                            IsCompleted = false,
                            OrderNumber = 4,
                            TechTaskPageId = 4
                        },
                        new
                        {
                            Id = 23,
                            Description = "М.б. создана <strong>страница с информацией о странах, об их географическом положении, об их достопримечательностях</strong>",
                            IsCompleted = false,
                            OrderNumber = 5,
                            TechTaskPageId = 4
                        },
                        new
                        {
                            Id = 24,
                            Description = "Дополнительно:\r\n							<br />М.б. создана <strong>страница с информацией о странах, об их истории, политическом устройстве, праве, традициях и обычаях местного населения, об объектах сферы гостеприимства (гостинницы, кафе и т.д.)</strong>",
                            IsCompleted = false,
                            OrderNumber = 6,
                            TechTaskPageId = 4
                        },
                        new
                        {
                            Id = 25,
                            Description = "Данная страница д. содержать:\r\n							<br/><strong>блок навигационных кнопок:</strong> \"Наши реквизиты\", \"Режим работы\", \"Фотогаллерея\", \"Обратная связь\", \"Edit AboutPage\", \"ТЗ для About\"\r\n							< br />< strong > блок рекизитов тур.фирмы </ strong >\r\n							< br />< strong > блок с информацией о режиме работы турфирмы </ strong >\r\n							< br />< strong > блок с фотографиями путешествий по странам мира </ strong > ",
                            IsCompleted = false,
                            OrderNumber = 1,
                            TechTaskPageId = 5
                        },
                        new
                        {
                            Id = 26,
                            Description = "Д.б. <strong>страница для создания, редактирования и удаления разных версий страницы About</strong>.\r\n							<br />Д.б. организован <strong>доступ к данной функциональности по ролям \"superadmin\", \"editor\"</strong>",
                            IsCompleted = false,
                            OrderNumber = 2,
                            TechTaskPageId = 5
                        },
                        new
                        {
                            Id = 27,
                            Description = "Д.б. <strong>страница с формой обратной связи с клиентами туристической фирмы</strong>\r\n							<br />Д.б. реализован <strong>функционал создания, отправки, сохранения вопросов от клиентов и просмотра  ответов на них от туристической фирмы</strong> (+ для боковой панели)",
                            IsCompleted = false,
                            OrderNumber = 3,
                            TechTaskPageId = 5
                        },
                        new
                        {
                            Id = 28,
                            Description = "Д.б. реализована возможность <strong>звонить из приложения и отправлять сообщения по email</strong> (+ для боковой панели)",
                            IsCompleted = false,
                            OrderNumber = 4,
                            TechTaskPageId = 5
                        },
                        new
                        {
                            Id = 29,
                            Description = "Д.б. реализована возможность <strong>общения с клиентами через социальные сети Facebook, WhatsApp, Telegram, Viber</strong> (+ для боковой панели)",
                            IsCompleted = false,
                            OrderNumber = 5,
                            TechTaskPageId = 5
                        },
                        new
                        {
                            Id = 30,
                            Description = "Дополнительно:\r\n							<br />М.б. реализован <strong>функционал подсчета стоимости поездки</strong> (+ для боковой панели)",
                            IsCompleted = false,
                            OrderNumber = 6,
                            TechTaskPageId = 5
                        });
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.TechTaskPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TechTaskPages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PageName = "Home"
                        },
                        new
                        {
                            Id = 2,
                            PageName = "Search"
                        },
                        new
                        {
                            Id = 3,
                            PageName = "Edit"
                        },
                        new
                        {
                            Id = 4,
                            PageName = "Support"
                        },
                        new
                        {
                            Id = 5,
                            PageName = "About"
                        },
                        new
                        {
                            Id = 6,
                            PageName = "Common"
                        });
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DateTourId")
                        .HasColumnType("integer");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DateTourId");

                    b.HasIndex("FoodId");

                    b.HasIndex("HotelId");

                    b.HasIndex("ProductId");

                    b.ToTable("Tour", (string)null);
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToursWebAppEXAMProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.City", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__City__CountryId__2D27B809");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Correspondence", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.Asker", "Asker")
                        .WithMany()
                        .HasForeignKey("AskerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asker");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Hotel", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK__Hotel__CityId__31EC6D26");

                    b.Navigation("City");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Offer", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.Customer", "Customer")
                        .WithMany("Offer")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Offer__Customer__4D94879B");

                    b.HasOne("ToursWebAppEXAMProject.Models.Saller", "Saller")
                        .WithMany("Offer")
                        .HasForeignKey("SallerId")
                        .IsRequired()
                        .HasConstraintName("FK__Offer__SallerId__4E88ABD4");

                    b.HasOne("ToursWebAppEXAMProject.Models.Tour", "Tour")
                        .WithMany("Offer")
                        .HasForeignKey("TourId")
                        .IsRequired()
                        .HasConstraintName("FK__Offer__TourId__4F7CD00D");

                    b.Navigation("Customer");

                    b.Navigation("Saller");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.PhotoGalleryImage", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.AboutPageVersion", "AboutPageVersion")
                        .WithMany("CollectionImages")
                        .HasForeignKey("AboutPageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutPageVersion");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Product", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.City", "City")
                        .WithMany("Products")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK__Products__CityId__34C8D9D1");

                    b.HasOne("ToursWebAppEXAMProject.Models.Country", "Country")
                        .WithMany("Products")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__Products__CountryId__35BCFE0A");

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.TechTaskItem", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.TechTaskPage", "TechTaskPage")
                        .WithMany("Tasks")
                        .HasForeignKey("TechTaskPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechTaskPage");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Tour", b =>
                {
                    b.HasOne("ToursWebAppEXAMProject.Models.DateTour", "DateTour")
                        .WithMany("Tours")
                        .HasForeignKey("DateTourId")
                        .IsRequired()
                        .HasConstraintName("FK__Tour__DateTourId__403A8C7D");

                    b.HasOne("ToursWebAppEXAMProject.Models.Food", "Food")
                        .WithMany("Tours")
                        .HasForeignKey("FoodId")
                        .IsRequired()
                        .HasConstraintName("FK__Tour__FoodId__4222D4EF");

                    b.HasOne("ToursWebAppEXAMProject.Models.Hotel", "Hotel")
                        .WithMany("Tours")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK__Tour__HotelId__412EB0B6");

                    b.HasOne("ToursWebAppEXAMProject.Models.Product", "Product")
                        .WithMany("Tours")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Tour__ProductId__3F466844");

                    b.Navigation("DateTour");

                    b.Navigation("Food");

                    b.Navigation("Hotel");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.AboutPageVersion", b =>
                {
                    b.Navigation("CollectionImages");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.City", b =>
                {
                    b.Navigation("Hotels");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Customer", b =>
                {
                    b.Navigation("Offer");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.DateTour", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Food", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Hotel", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Product", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Saller", b =>
                {
                    b.Navigation("Offer");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.TechTaskPage", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ToursWebAppEXAMProject.Models.Tour", b =>
                {
                    b.Navigation("Offer");
                });
#pragma warning restore 612, 618
        }
    }
}
